### ISSUE TITLE
Server mobius error

### ISSUE THREAD

**Issue by kimoudev** [IoTKETI/Mobius#13]
Hi,
 I have this error.
I also have mosquitto authenticate enable.
How to set username and password MQTT in app? Please

```
events.js:160
      throw er; // Unhandled 'error' event
 Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/var/www/Mobius/node_modules/mqtt/lib/client.js:879:15)
    at MqttClient._handlePacket (/var/www/Mobius/node_modules/mqtt/lib/client.js:318:12)
    at work (/var/Mobius/node_modules/mqtt/lib/client.js:260:12)
    at Writable.writable._write (/var/www/Mobius/node_modules/mqtt/lib/client.js:270:5)
    at doWrite (/var/www/Mobius/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/var/wwwMobius/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at Writable.write (/var/www/Mobius/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

**Comment by UniverseHan** [comment]
It may be username:passwor@host helpfull

**Comment by kimoudev** [comment]
Hi @UniverseHan  @IoTKETI 
it happens when I start the Mobius server with authenticate enable.
Please, do you have an idea of the file where set the authenticate params?
Thanks,

**Comment by kimoudev** [comment]
Thank @UniverseHan

**Comment by UniverseHan** [comment]
Was it helped? @kimoudev

**Comment by rkarma69** [comment]
Hi Guys
I have the same one. how to and where to set it up?
I could not find it in client.js.
Thanks in advance.
